In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('hiring.csv')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [3]:
df.rename(columns={'test_score(out of 10)': 'test'}, inplace=True)
df.rename(columns={'interview_score(out of 10)': 'interview'}, inplace=True)
df.rename(columns={'salary($)': 'salary'}, inplace=True)
maping = {'five' : 5, 'two':2, 'seven': 7, 'three' : 3, 'ten':10, 'eleven':11}
df['experience'] = df['experience'].map(maping)
df['test'] = df['test'].astype(float)
df

experience  test  interview  salary
0         NaN   8.0          9   50000
1         NaN   8.0          6   45000
2         5.0   6.0          7   60000
3         2.0  10.0         10   65000
4         7.0   9.0          6   70000
5         3.0   7.0         10   62000
6        10.0   NaN          7   72000
7        11.0   7.0          8   80000

In [4]:
df1 = df.dropna()
df1 = pd.DataFrame(df1)
df1

experience  test  interview  salary
2         5.0   6.0          7   60000
3         2.0  10.0         10   65000
4         7.0   9.0          6   70000
5         3.0   7.0         10   62000
7        11.0   7.0          8   80000

In [5]:
X = df1.drop(['test', 'experience'], axis = 'columns')
X

interview  salary
2          7   60000
3         10   65000
4          6   70000
5         10   62000
7          8   80000

In [6]:
y = df1.test
y

2     6.0
3    10.0
4     9.0
5     7.0
7     7.0
Name: test, dtype: float64

In [7]:
reg1 = linear_model.LinearRegression()
reg1.fit(X,y)

LinearRegression()

In [8]:
df2 = df[df['test'].isnull()]
predicted_values = reg1.predict(df2[['interview', 'salary']])
df.loc[df['test'].isnull(), 'test'] = predicted_values


In [9]:
df3 = df.dropna()
df3

experience       test  interview  salary
2         5.0   6.000000          7   60000
3         2.0  10.000000         10   65000
4         7.0   9.000000          6   70000
5         3.0   7.000000         10   62000
6        10.0   7.700551          7   72000
7        11.0   7.000000          8   80000

In [10]:
X = df3.drop(['experience'], axis=1)
X.dtypes

test         float64
interview      int64
salary         int64
dtype: object

In [11]:
y = df3['experience']
y

2     5.0
3     2.0
4     7.0
5     3.0
6    10.0
7    11.0
Name: experience, dtype: float64

In [12]:
reg2 = linear_model.LinearRegression()
reg2.fit(X,y)

LinearRegression()

In [13]:
reg2.predict([[8.000000, 6, 45000]])

C:\Users\Ravi Galathiya\AppData\Roaming\Python\Python38\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([-1.37266295])

In [14]:
df3 = df[df['experience'].isnull()]
predicted_values = reg2.predict(df3[['test', 'interview', 'salary']])

In [15]:
df.fillna('0', inplace = True)
df['experience'] = df['experience'].astype(float)
df

experience       test  interview  salary
0         0.0   8.000000          9   50000
1         0.0   8.000000          6   45000
2         5.0   6.000000          7   60000
3         2.0  10.000000         10   65000
4         7.0   9.000000          6   70000
5         3.0   7.000000         10   62000
6        10.0   7.700551          7   72000
7        11.0   7.000000          8   80000

In [19]:
X = df.drop(['salary'], axis = 1)
X

experience       test  interview
0         0.0   8.000000          9
1         0.0   8.000000          6
2         5.0   6.000000          7
3         2.0  10.000000         10
4         7.0   9.000000          6
5         3.0   7.000000         10
6        10.0   7.700551          7
7        11.0   7.000000          8

In [21]:
y = df['salary']
y

0    50000
1    45000
2    60000
3    65000
4    70000
5    62000
6    72000
7    80000
Name: salary, dtype: int64

In [22]:
reg = linear_model.LinearRegression()
reg.fit(X,y)

LinearRegression()

In [23]:
reg.predict([[0.0, 8.000000, 9]])

C:\Users\Ravi Galathiya\AppData\Roaming\Python\Python38\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([52272.86350991])

In [26]:
reg.coef_

array([2844.30008746, 1982.48126566, 2187.7975003 ])

In [27]:
reg.intercept_

16722.83588194415